### ISSUE TITLE
Should we add help text?

### ISSUE THREAD

**Issue by ryasmi** [chrisandryan/Budgeter#7]
Should we add some help text somewhere in the UI (perhaps at the bottom)? It could be used to display errors, warnings, instructions, tips, etc.

**Comment by chrisandryan** [comment]
We dont want help there all the time tho. But help is defiantly needed. Maybe a help button in the settings or a more sophisticated context sensitive help using XML with the name of the current view as the XML tag.

**Comment by ryasmi** [comment]
Ok, context sensitive sounds good to me.
