### ISSUE TITLE
Where to store data?

### ISSUE THREAD

**Issue by ryasmi** [chrisandryan/Budgeter#8]
Where are we going to store data (see scenario 1 and 2)? I'm not entirely sure if android does anything to help us here.

**Scenario 1**: User sells old device and buys a new one (in that order). Therefore the user cannot transfer the data from the old device to the new one.
**Scenario 2**: User gets new device to coexist with their current one. Therefore the data needs to be on two devices at once and needs to be up to date on both.

I know you previously mentioned dropbox, but this would require the user to sign up to dropbox if they haven't already. I think it would instead be better to use a Google service using their Google account (which they probably have using an android device). I that means we put all their data in Google's hands, but I don't think that will be an issue.

**Comment by chrisandryan** [comment]
Sounds like a good idea to me. Will require some investigation into google services

**Comment by ryasmi** [comment]
Ok, I will post any findings in comments here.

**Comment by ryasmi** [comment]
@chrisandryan Looks to me like Android has us covered (but not by default).
[Backup API](http://developer.android.com/training/cloudsync/backupapi.html)
[Backup Service](https://developer.android.com/google/backup/index.html)
[Registration for Backup Service](https://developer.android.com/google/backup/signup.html)
