### ISSUE TITLE
Do we need a licence?

### ISSUE THREAD

**Issue by ryasmi** [chrisandryan/Budgeter#9]
As this is a public repository we should probably get a licence from Creative Commons and stick the text into a file named "LICENCE" (to go with the convention).

**Comment by chrisandryan** [comment]
Can I leave that on with u then. You seem to know what ure doing.

**Comment by ryasmi** [comment]
Yeah. I'm doing it now. [Attribution-NonCommercial-NoDerivs 3.0 Unported (CC BY-NC-ND 3.0)](http://creativecommons.org/licenses/by-nc-nd/3.0/).

**Licence features:**
1. Allow modifications of your work? No.
2. Allow commercial uses of your work? No.
3. License Jurisdiction: International.

**Explanation of features:**
1. The licensor permits others to copy, distribute, display and perform only unaltered copies of the work, but not create and distribute derivative works based on it.
2. The licensor permits others to copy, distribute, display, and perform the work for non-commercial purposes only.
